export const GET_ALL_POSTS_REQUEST = 'GET_ALL_POSTS_REQUEST'
export const GET_ALL_POSTS_SUCCESS = 'GET_ALL_POSTS_SUCCESS'
export const GET_ALL_POSTS_FAIL = 'GET_ALL_POSTS_FAIL'

export const GET_POSTS_REQUEST = 'GET_POSTS_REQUEST'
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS'
export const GET_POSTS_FAIL = 'GET_POSTS_FAIL'

export const GET_POST_BY_ID_REQUEST = 'GET_POST_BY_ID_REQUEST'
export const GET_POST_BY_ID_SUCCESS = 'GET_POST_BY_ID_SUCCESS'
export const GET_POST_BY_ID_FAIL = 'GET_POST_BY_ID_FAIL'

export const GET_POST_BY_CAT_REQUEST = 'GET_POST_BY_CAT_REQUEST'
export const GET_POST_BY_CAT_SUCCESS = 'GET_POST_BY_CAT_SUCCESS'
export const GET_POST_BY_CAT_FAIL = 'GET_POST_BY_CAT_FAIL'

export const GET_POST_BY_LAN_REQUEST = 'GET_POST_BY_LAN_REQUEST'
export const GET_POST_BY_LAN_SUCCESS = 'GET_POST_BY_LAN_SUCCESS'
export const GET_POST_BY_LAN_FAIL = 'GET_POST_BY_LAN_FAIL'

export const COMMENT_POST_REQUEST = 'COMMENT_POST_REQUEST'
export const COMMENT_POST_SUCCESS = 'COMMENT_POST_SUCCESS'
export const COMMENT_POST_FAIL = 'COMMENT_POST_FAIL'


export const GET_COMMENTS_REQUEST = 'GET_COMMENTS_REQUEST'
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS'
export const GET_COMMENTS_FAIL = 'GET_COMMENTS_FAIL'

export const CREATE_NEW_POST_REQUEST = 'CREATE_NEW_POST_REQUEST'
export const CREATE_NEW_POST_SUCCESS = 'CREATE_NEW_POST_SUCCESS'
export const CREATE_NEW_POST_FAIL = 'CREATE_NEW_POST_FAIL'


export const UPDATE_NEW_POST_REQUEST = 'UPDATE_NEW_POST_REQUEST'
export const UPDATE_NEW_POST_SUCCESS = 'UPDATE_NEW_POST_SUCCESS'
export const UPDATE_NEW_POST_FAIL = 'UPDATE_NEW_POST_FAIL'


export const DETETE_POST_REQUEST = 'DETETE_POST_REQUEST'
export const DETETE_POST_SUCCESS = 'DETETE_POST_SUCCESS'
export const DETETE_POST_FAIL = 'DETETE_POST_FAIL'








